services:
  patient-service:
    build:
      context: . # is /patient-management-msa
      dockerfile: patient-service/dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://patient-service-db:5432/${PATIENT_SERVICE_DB}
      - SPRING_DATASOURCE_USERNAME=${PATIENT_SERVICE_DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${PATIENT_SERVICE_DB_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_SQL_INIT_MODE=always
      - BILLING_SERVICE_ADDRESS=billing-service
      - BILLING_SERVICE_GRPC_PORT=9001
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    expose:
      - ${PATIENT_SERVICE_PORT}:4000
    networks:
      - patient-management-msa
    # healthcheck:

    depends_on:
      patient-service-db:
        condition: service_healthy
      kafka:
        condition: service_healthy

  billing-service:
    build:
      context: .
      dockerfile: billing-service/dockerfile
    # environment:

    expose:
      - ${BILLING_SERVICE_PORT}:4001
      - ${GRPC_SERVER_PORT}:9001
    networks:
      - patient-management-msa
    # healthcheck:

    # depends_on:

  analytics-service:
    build:
      context: .
      dockerfile: analytics-service/dockerfile
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    expose:
      - ${ANALYTICS_SERVICE_PORT}:4002
    networks:
      - patient-management-msa
    # healthcheck:

    depends_on:
      kafka:
        condition: service_healthy

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/dockerfile
    environment:
      - AUTH_SERVICE_URL=http://auth-service:${AUTH_SERVICE_PORT:-4004}
    ports:
      - "${API_GATEWAY_PORT}:4003"
    networks:
      - patient-management-msa
    # healthcheck:

    depends_on:
      patient-service:
        condition: service_started

  auth-service:
    build:
      context: .
      dockerfile: auth-service/dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://auth-service-db:5432/${AUTH_SERVICE_DB}
      - SPRING_DATASOURCE_USERNAME=${AUTH_SERVICE_DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${AUTH_SERVICE_DB_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_SQL_INIT_MODE=always
      - JWT_SECRET=${JWT_SECRET}
    expose:
      - ${AUTH_SERVICE_PORT}:4004
    networks:
      - patient-management-msa
    # healthcheck:

    depends_on:
      auth-service-db:
        condition: service_healthy

  # Kafka Broker

  kafka:
    image: confluentinc/cp-kafka:latest
    environment:
      - KAFKA_NODE_ID=0
      - KAFKA_PROCESS_ROLES=controller,broker # are the roles of the Kafka container
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,EXTERNAL://0.0.0.0:9400
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9400
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    expose: # inside the docker network
      - ${KAFKA_INTERNAL_PORT}:9092
    ports: # outside the docker network 
      - ${KAFKA_DEVELOPMENT_PORT}:9400
    networks:
      - patient-management-msa
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions", "--bootstrap-server", "kafka:9092"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # PostgreSQL DB

  patient-service-db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${PATIENT_SERVICE_DB_USER}
      - POSTGRES_PASSWORD=${PATIENT_SERVICE_DB_PASSWORD}
      - POSTGRES_DB=${PATIENT_SERVICE_DB}
    ports:
      - ${PATIENT_SERVICE_DB_PORT}:5432
    volumes: # Named volume
      - ${PATIENT_SERVICE_DB_DATA}:/var/lib/postgresql
    networks:
      - patient-management-msa
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U ${PATIENT_SERVICE_DB_USER} -d ${PATIENT_SERVICE_DB}"]
      interval: 10s # Run the health check every x seconds
      timeout: 5s # A time limit of x seconds before marking the attempt as failed
      retries: 5 # Number of allowed failed attempts in a row before marking the container as unhealthy
      start_period: 30s # Warm-up time for the container before docker starts counting failures

  auth-service-db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${AUTH_SERVICE_DB_USER}
      - POSTGRES_PASSWORD=${AUTH_SERVICE_DB_PASSWORD}
      - POSTGRES_DB=${AUTH_SERVICE_DB}
    ports:
      - ${AUTH_SERVICE_DB_PORT}:5432
    volumes: # Named volume
      - ${AUTH_SERVICE_DB_DATA}:/var/lib/postgresql
    networks:
      - patient-management-msa
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U ${AUTH_SERVICE_DB_USER} -d ${AUTH_SERVICE_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  ministack:
    image: ministackorg/ministack:latest
    container_name: ministack-aws-local
    ports:
      - "4566:4566"
    environment:
      - DEBUG=1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - patient-management-msa

volumes:
  patient-service-db-data:
  auth-service-db-data:

networks:
  patient-management-msa:
    name: patient-management-msa
    driver: bridge