services:
  patient-service:
    build:
      context: . # is /patient-management-msa
      dockerfile: patient-service/dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://patient-service-db:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_SQL_INIT_MODE=always
      - BILLING_SERVICE_ADDRESS=billing-service
      - BILLING_SERVICE_GRPC_PORT=${GRPC_SERVER_PORT}
    ports:
      - ${PATIENT_SERVICE_PORT}:4000
    networks:
      - patient-management-msa
    depends_on:
      patient-service-db:
        condition: service_healthy
  
  patient-service-db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes: # Named volume
      - ${POSTGRES_DATA}:/var/lib/postgresql
    networks:
      - patient-management-msa
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s # Run the health check every x seconds
      timeout: 5s # A time limit of x seconds before marking the attempt as failed
      retries: 5 # Number of allowed failed attempts in a row before marking the container as unhealthy
      start_period: 30s # Warm-up time for the container before docker starts counting failures

  billing-service:
    build:
      context: .
      dockerfile: billing-service/dockerfile
    # environment:

    ports:
      - ${BILLING_SERVICE_PORT}:4001
      - ${GRPC_SERVER_PORT}:9001
    networks:
      - patient-management-msa
    # depends_on:

  kafka:
    image: confluentinc/cp-kafka:latest
    environment:
      - KAFKA_NODE_ID=0
      - KAFKA_PROCESS_ROLES=controller,broker # are the roles of the Kafka container
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,EXTERNAL://0.0.0.0:9222
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9222
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    ports:
      - ${KAFKA_INTERNAL_PORT}:9092 # inside the docker network
      - ${KAFKA_DEVELOPMENT_PORT}:9222 # outside the docker network 
    networks:
      - patient-management-msa

volumes:
  patient-service-db-data:

networks:
  patient-management-msa:
    name: patient-management-msa
    driver: bridge