FROM maven:3.9.16-eclipse-temurin-21 AS builder

WORKDIR /app

# Copy all POM files because root POM is an Aggregator that declares all modules
COPY pom.xml .
COPY protobuf-contracts/pom.xml ./protobuf-contracts/pom.xml
COPY patient-service/pom.xml ./patient-service/pom.xml
COPY billing-service/pom.xml ./billing-service/pom.xml
COPY analytics-service/pom.xml ./analytics-service/pom.xml
COPY api-gateway/pom.xml ./api-gateway/pom.xml
COPY auth-service/pom.xml ./auth-service/pom.xml

# Download all dependencies (offline cache) before copying source code to leverage Docker layer caching
RUN mvn dependency:go-offline -pl auth-service -am -B

COPY auth-service/src ./auth-service/src

# -pl specifies the module to build (auth-service)
# -am builds all modules that the specified module depends on (protobuf-contracts)
RUN mvn clean package -pl auth-service -am -B -DskipTests

FROM eclipse-temurin:21-jre AS runner

WORKDIR /app

COPY --from=builder /app/auth-service/target/auth-service-0.0.1-SNAPSHOT.jar ./app.jar

EXPOSE ${AUTH_SERVICE_PORT}

ENTRYPOINT ["java", "-jar", "app.jar"]