FROM maven:3.9.16-eclipse-temurin-21 AS builder

WORKDIR /app

# Copy all POM files because root POM is an Aggregator that declares all modules
COPY pom.xml .
COPY protobuf-contracts/pom.xml ./protobuf-contracts/pom.xml
COPY patient-service/pom.xml ./patient-service/pom.xml
COPY billing-service/pom.xml ./billing-service/pom.xml

# Download all dependencies (offline cache) before copying source code to leverage Docker layer caching
RUN mvn dependency:go-offline -pl patient-service -am -B

# patient-service is dependent on protobuf-contracts
COPY protobuf-contracts/src ./protobuf-contracts/src
COPY patient-service/src ./patient-service/src

# -pl specifies the module to build (patient-service)
# -am builds all modules that the specified module depends on (protobuf-contracts)
RUN mvn clean package -pl patient-service -am -B -DskipTests

FROM eclipse-temurin:21-jre AS runner

WORKDIR /app

COPY --from=builder /app/patient-service/target/patient-service-0.0.1-SNAPSHOT.jar ./app.jar

EXPOSE 4000

ENTRYPOINT ["java", "-jar", "app.jar"]