FROM maven:3.9.16-eclipse-temurin-21 AS builder

WORKDIR /app

COPY pom.xml .

# Cache dependencies
RUN mvn dependency:go-offline -B

COPY src ./src
RUN mvn clean package

FROM eclipse-temurin:21-jre AS runner

WORKDIR /app

COPY --from=builder /app/target/billing-service-0.0.1-SNAPSHOT.jar ./app.jar

# REST server port
EXPOSE 4001
# gRPC server port
EXPOSE 9001

# Use java stay alive (from jdk) to keep the container running
ENTRYPOINT ["java", "-jar", "app.jar"]